name: publish

on:
  push:
    branches: ["manim"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install manim dependencies
        run: sudo apt -y update && sudo apt -y install build-essential python3-dev libcairo2-dev libpango1.0-dev ffmpeg

      - name: Install manim and manim-slides
        run: cd manim && pip install -r requirements.txt

      - name: Compile scenes
        run: cd manim && manim -qh simplepir.py SimplePIR

      - name: Compile slides
        run: cd manim && manim-slides convert SimplePIR --to=html ./slides/slides.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./manim/slides/

