name: publish

on:
  push:
    branches: ["manim"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install manim and manim-slides
        run: cd manim && pip install -r requirements.txt

      #- name: Deploy to GitHub Pages
        #uses: peaceiris/actions-gh-pages@v3
        #with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          #publish_dir: ./docs/book/html

